import { Router, type IRouter } from "express";

const router: IRouter = Router();

export const WILAYAS = [
  { code: "01", name: "Adrar", nameAr: "أدرار", region: "Sud-Ouest", deliveryFee: 800 },
  { code: "02", name: "Chlef", nameAr: "الشلف", region: "Nord", deliveryFee: 400 },
  { code: "03", name: "Laghouat", nameAr: "الأغواط", region: "Centre", deliveryFee: 600 },
  { code: "04", name: "Oum El Bouaghi", nameAr: "أم البواقي", region: "Nord-Est", deliveryFee: 500 },
  { code: "05", name: "Batna", nameAr: "باتنة", region: "Nord-Est", deliveryFee: 450 },
  { code: "06", name: "Béjaïa", nameAr: "بجاية", region: "Nord-Est", deliveryFee: 450 },
  { code: "07", name: "Biskra", nameAr: "بسكرة", region: "Centre-Est", deliveryFee: 550 },
  { code: "08", name: "Béchar", nameAr: "بشار", region: "Sud-Ouest", deliveryFee: 750 },
  { code: "09", name: "Blida", nameAr: "البليدة", region: "Nord", deliveryFee: 350 },
  { code: "10", name: "Bouira", nameAr: "البويرة", region: "Nord", deliveryFee: 400 },
  { code: "11", name: "Tamanrasset", nameAr: "تمنراست", region: "Grand Sud", deliveryFee: 900 },
  { code: "12", name: "Tébessa", nameAr: "تبسة", region: "Nord-Est", deliveryFee: 500 },
  { code: "13", name: "Tlemcen", nameAr: "تلمسان", region: "Nord-Ouest", deliveryFee: 450 },
  { code: "14", name: "Tiaret", nameAr: "تيارت", region: "Nord-Ouest", deliveryFee: 500 },
  { code: "15", name: "Tizi Ouzou", nameAr: "تيزي وزو", region: "Nord", deliveryFee: 400 },
  { code: "16", name: "Alger", nameAr: "الجزائر", region: "Nord", deliveryFee: 300 },
  { code: "17", name: "Djelfa", nameAr: "الجلفة", region: "Centre", deliveryFee: 550 },
  { code: "18", name: "Jijel", nameAr: "جيجل", region: "Nord-Est", deliveryFee: 450 },
  { code: "19", name: "Sétif", nameAr: "سطيف", region: "Nord-Est", deliveryFee: 400 },
  { code: "20", name: "Saïda", nameAr: "سعيدة", region: "Nord-Ouest", deliveryFee: 500 },
  { code: "21", name: "Skikda", nameAr: "سكيكدة", region: "Nord-Est", deliveryFee: 450 },
  { code: "22", name: "Sidi Bel Abbès", nameAr: "سيدي بلعباس", region: "Nord-Ouest", deliveryFee: 450 },
  { code: "23", name: "Annaba", nameAr: "عنابة", region: "Nord-Est", deliveryFee: 400 },
  { code: "24", name: "Guelma", nameAr: "قالمة", region: "Nord-Est", deliveryFee: 450 },
  { code: "25", name: "Constantine", nameAr: "قسنطينة", region: "Nord-Est", deliveryFee: 400 },
  { code: "26", name: "Médéa", nameAr: "المدية", region: "Nord", deliveryFee: 400 },
  { code: "27", name: "Mostaganem", nameAr: "مستغانم", region: "Nord-Ouest", deliveryFee: 450 },
  { code: "28", name: "M'Sila", nameAr: "المسيلة", region: "Centre", deliveryFee: 500 },
  { code: "29", name: "Mascara", nameAr: "معسكر", region: "Nord-Ouest", deliveryFee: 500 },
  { code: "30", name: "Ouargla", nameAr: "ورقلة", region: "Sud", deliveryFee: 700 },
  { code: "31", name: "Oran", nameAr: "وهران", region: "Nord-Ouest", deliveryFee: 350 },
  { code: "32", name: "El Bayadh", nameAr: "البيض", region: "Sud-Ouest", deliveryFee: 650 },
  { code: "33", name: "Illizi", nameAr: "إليزي", region: "Grand Sud", deliveryFee: 950 },
  { code: "34", name: "Bordj Bou Arréridj", nameAr: "برج بوعريريج", region: "Nord-Est", deliveryFee: 450 },
  { code: "35", name: "Boumerdès", nameAr: "بومرداس", region: "Nord", deliveryFee: 350 },
  { code: "36", name: "El Tarf", nameAr: "الطارف", region: "Nord-Est", deliveryFee: 450 },
  { code: "37", name: "Tindouf", nameAr: "تندوف", region: "Grand Sud", deliveryFee: 950 },
  { code: "38", name: "Tissemsilt", nameAr: "تيسمسيلت", region: "Nord-Ouest", deliveryFee: 550 },
  { code: "39", name: "El Oued", nameAr: "الوادي", region: "Sud-Est", deliveryFee: 650 },
  { code: "40", name: "Khenchela", nameAr: "خنشلة", region: "Nord-Est", deliveryFee: 500 },
  { code: "41", name: "Souk Ahras", nameAr: "سوق أهراس", region: "Nord-Est", deliveryFee: 500 },
  { code: "42", name: "Tipaza", nameAr: "تيبازة", region: "Nord", deliveryFee: 350 },
  { code: "43", name: "Mila", nameAr: "ميلة", region: "Nord-Est", deliveryFee: 450 },
  { code: "44", name: "Aïn Defla", nameAr: "عين الدفلى", region: "Nord", deliveryFee: 450 },
  { code: "45", name: "Naâma", nameAr: "النعامة", region: "Sud-Ouest", deliveryFee: 650 },
  { code: "46", name: "Aïn Témouchent", nameAr: "عين تموشنت", region: "Nord-Ouest", deliveryFee: 450 },
  { code: "47", name: "Ghardaïa", nameAr: "غرداية", region: "Sud", deliveryFee: 650 },
  { code: "48", name: "Relizane", nameAr: "غليزان", region: "Nord-Ouest", deliveryFee: 450 },
  { code: "49", name: "Timimoun", nameAr: "تيميمون", region: "Sud-Ouest", deliveryFee: 850 },
  { code: "50", name: "Bordj Badji Mokhtar", nameAr: "برج باجي مختار", region: "Grand Sud", deliveryFee: 950 },
  { code: "51", name: "Ouled Djellal", nameAr: "أولاد جلال", region: "Centre", deliveryFee: 600 },
  { code: "52", name: "Béni Abbès", nameAr: "بني عباس", region: "Sud-Ouest", deliveryFee: 800 },
  { code: "53", name: "In Salah", nameAr: "عين صالح", region: "Grand Sud", deliveryFee: 900 },
  { code: "54", name: "In Guezzam", nameAr: "عين قزام", region: "Grand Sud", deliveryFee: 950 },
  { code: "55", name: "Touggourt", nameAr: "تقرت", region: "Sud-Est", deliveryFee: 700 },
  { code: "56", name: "Djanet", nameAr: "جانت", region: "Grand Sud", deliveryFee: 950 },
  { code: "57", name: "El M'Ghair", nameAr: "المغير", region: "Sud-Est", deliveryFee: 700 },
  { code: "58", name: "El Meniaa", nameAr: "المنيعة", region: "Sud", deliveryFee: 750 },
];

router.get("/wilayas", (_req, res) => {
  res.json(WILAYAS);
});

export default router;
